# -*- coding: utf-8 -*-
"""datamining

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_lFfR2KLKH9_9zLesDgSORs_OMMtoCjL
"""

import numpy as np
import pandas as pd

# ------------------------------------------
# 1. Read Student Details Dataset

df1 = pd.read_csv(r"/content/Student_Details_Dataset_100rows_with_nulls_updated.csv")
print("Student Details Dataset:")
print(df1)

# ------------------------------------------
# 2. Read Events Participation Dataset

df2 = pd.read_csv(r"/content/Events_Participation_Dataset_100rows.csv")
print("\nEvents Participation Dataset:")
print(df2)

# ---------------------------------------------
# 3. Cleaning NaN Values in "Year" Column

before_cleaning = df1['Year']
print("\nYear Column Before Cleaning:")
print(before_cleaning)

after_cleaning = df1['Year'].dropna()
print("\nYear Column After Cleaning (NaN Removed):")
print(after_cleaning)

# ---------------------------------------------
# 4. Merge Both Datasets using StudentID

merged_df = pd.merge(df1, df2, on='StudentID', how='inner')

print("\nMerged Dataset (Full Rows):")
print(merged_df)

# ---------------------------------------------
# 5. Add Performance Column (Winner = Excellent, Participant = Average)

def performance_category(row):
    if row['ParticipationType'] == "Winner":
        return "Excellent"
    else:
        return "Average"

merged_df['Performance'] = merged_df.apply(performance_category, axis=1)

# ---------------------------------------------
# 6. Display Entire Student Row with Performance Condition

print("\nFinal Student Rows with Performance Column Applied:\n")
print(merged_df[['StudentID', 'StudentName', 'Year',
                 'EventName', 'ParticipationType', 'Performance']])

# ---------------------------------------------
# 7. Rank Mapping Based on Performance

rank_map = {
    "Excellent": 1,
    "Average": 2
}

merged_df['Rank'] = merged_df['Performance'].map(rank_map)

# ---------------------------------------------
# 8. Sort Dataset by Rank

merged_df = merged_df.sort_values('Rank')

print("\nFinal Sorted Dataset with Full Student Rows:\n")
print(merged_df)

# ---------------------------------------------
# 9. Save Final Output CSV

merged_df.to_csv("final_student_performance.csv", index=False)

print("\nFinal Student Performance File Saved as: final_student_performance.csv")

import pandas as pd
import matplotlib.pyplot as plt

# Load Dataset (Before Cleaning)
df = pd.read_csv(r"/content/Student_Details_Dataset_100rows_with_nulls_updated.csv")

# Plot Entire Dataset Year Distribution (Including NaN)
plt.figure(figsize=(10,6))

df['Year'].value_counts(dropna=False).plot(kind='bar')

plt.title("Entire Dataset Graph BEFORE Cleaning (Year Column)")
plt.xlabel("Year Values (Including NaN)")
plt.ylabel("Number of Students")

plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# Load Dataset
df = pd.read_csv(r"/content/Student_Details_Dataset_100rows_with_nulls_updated.csv")

# Cleaning: Remove NaN Values from Year Column
df_cleaned = df.dropna(subset=['Year'])

# Plot Entire Dataset Year Distribution (After Cleaning)
plt.figure(figsize=(10,6))

df_cleaned['Year'].value_counts().plot(kind='bar')

plt.title("Entire Dataset Graph AFTER Cleaning (Year Column)")
plt.xlabel("Year Values")
plt.ylabel("Number of Students")

plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# Load Dataset (Before Cleaning)
df = pd.read_csv(r"/content/Student_Details_Dataset_100rows_with_nulls_updated.csv")

# Scatter Plot Before Cleaning
plt.figure(figsize=(12,6))

plt.scatter(df.index, df['Year'])

plt.title("Scatter Plot BEFORE Cleaning (Year Column - 100 Students)")
plt.xlabel("Student Index (0 to 99)")
plt.ylabel("Year Values (Including NaN)")

plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# Load Dataset
df = pd.read_csv(r"/content/Student_Details_Dataset_100rows_with_nulls_updated.csv")

# Remove NaN Values (Cleaning)
df_cleaned = df.dropna(subset=['Year'])

# Scatter Plot After Cleaning
plt.figure(figsize=(12,6))

plt.scatter(df_cleaned.index, df_cleaned['Year'])

plt.title("Scatter Plot AFTER Cleaning (Year Column - NaN Removed)")
plt.xlabel("Student Index")
plt.ylabel("Year Values")

plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# -------------------------------
# Load Dataset
df1 = pd.read_csv(r"/content/Student_Details_Dataset_100rows_with_nulls_updated.csv")

# -------------------------------
# Year Column BEFORE Cleaning
before_cleaning = df1['Year']

# Year Column AFTER Cleaning (Remove NaN)
after_cleaning = df1.dropna(subset=['Year'])

# -------------------------------
# Create Split Scatter Plot Figure
plt.figure(figsize=(16,7))

# =====================================================
# LEFT SIDE: BEFORE CLEANING
plt.subplot(1, 2, 1)

plt.scatter(df1.index, before_cleaning)

plt.title("Scatter Plot BEFORE Cleaning\n(Year Column – 100 Students)",
          fontsize=13, fontweight="bold")

plt.xlabel("Student Index (0 to 99)", fontsize=11)
plt.ylabel("Year Values (including NaN)", fontsize=11)

# Annotation for Missing Values
plt.annotate("Missing Values (NaN)",
             xy=(30, 1.8), xytext=(35, 2.2),
             arrowprops=dict(arrowstyle="->", lw=2),
             fontsize=12)

# =====================================================
# RIGHT SIDE: AFTER CLEANING
plt.subplot(1, 2, 2)

plt.scatter(after_cleaning.index, after_cleaning['Year'])

plt.title("Scatter Plot AFTER Cleaning\n(Year Column – NaN Removed)",
          fontsize=13, fontweight="bold")

plt.xlabel("Student Index", fontsize=11)
plt.ylabel("Year Values", fontsize=11)

# Annotation for Cleaned Data
plt.annotate("Cleaned Data\n(No Gaps)",
             xy=(after_cleaning.index[-1], after_cleaning['Year'].iloc[-1]),
             xytext=(50, 3.8),
             arrowprops=dict(arrowstyle="->", lw=2),
             fontsize=12)

# =====================================================
# MAIN TITLE (Like Image Heading)
plt.suptitle("BEFORE vs. AFTER DATA CLEANING",
             fontsize=18, fontweight="bold")

# Adjust Layout
plt.tight_layout(rect=[0, 0, 1, 0.93])

plt.show()
# =========================================================

# Graph plots Before and After 

#===========================================================
import pandas as pd
import matplotlib.pyplot as plt

# Load Dataset (Before Cleaning)
df = pd.read_csv(r"/content/Student_Details_Dataset_100rows_with_nulls_updated.csv")

# Plot Entire Dataset Year Distribution (Including NaN)
plt.figure(figsize=(10,6))

df['Year'].value_counts(dropna=False).plot(kind='bar')

plt.title("Entire Dataset Graph BEFORE Cleaning (Year Column)")
plt.xlabel("Year Values (Including NaN)")
plt.ylabel("Number of Students")

plt.show()

#=================================================================

import pandas as pd
import matplotlib.pyplot as plt

# Load Dataset
df = pd.read_csv(r"/content/Student_Details_Dataset_100rows_with_nulls_updated.csv")

# Cleaning: Remove NaN Values from Year Column
df_cleaned = df.dropna(subset=['Year'])

# Plot Entire Dataset Year Distribution (After Cleaning)
plt.figure(figsize=(10,6))

df_cleaned['Year'].value_counts().plot(kind='bar')

plt.title("Entire Dataset Graph AFTER Cleaning (Year Column)")
plt.xlabel("Year Values")
plt.ylabel("Number of Students")

plt.show()

# ========================================================================

#Scatter plot Before and AFter cleanining

#==========================================================================

import pandas as pd
import matplotlib.pyplot as plt

# -------------------------------
# Load Dataset
df1 = pd.read_csv(r"/content/Student_Details_Dataset_100rows_with_nulls_updated.csv")

# -------------------------------
# Year Column BEFORE Cleaning
before_cleaning = df1['Year']

# Year Column AFTER Cleaning (Remove NaN)
after_cleaning = df1.dropna(subset=['Year'])

# -------------------------------
# Create Split Scatter Plot Figure
plt.figure(figsize=(16,7))

# =====================================================
# LEFT SIDE: BEFORE CLEANING
plt.subplot(1, 2, 1)

plt.scatter(df1.index, before_cleaning)

plt.title("Scatter Plot BEFORE Cleaning\n(Year Column – 100 Students)",
          fontsize=13, fontweight="bold")

plt.xlabel("Student Index (0 to 99)", fontsize=11)
plt.ylabel("Year Values (including NaN)", fontsize=11)

# Annotation for Missing Values
plt.annotate("Missing Values (NaN)",
             xy=(30, 1.8), xytext=(35, 2.2),
             arrowprops=dict(arrowstyle="->", lw=2),
             fontsize=12)

# =====================================================
# RIGHT SIDE: AFTER CLEANING
plt.subplot(1, 2, 2)

plt.scatter(after_cleaning.index, after_cleaning['Year'])

plt.title("Scatter Plot AFTER Cleaning\n(Year Column – NaN Removed)",
          fontsize=13, fontweight="bold")

plt.xlabel("Student Index", fontsize=11)
plt.ylabel("Year Values", fontsize=11)

# Annotation for Cleaned Data
plt.annotate("Cleaned Data\n(No Gaps)",
             xy=(after_cleaning.index[-1], after_cleaning['Year'].iloc[-1]),
             xytext=(50, 3.8),
             arrowprops=dict(arrowstyle="->", lw=2),
             fontsize=12)

# =====================================================
# MAIN TITLE (Like Image Heading)
plt.suptitle("BEFORE vs. AFTER DATA CLEANING",
             fontsize=18, fontweight="bold")

# Adjust Layout
plt.tight_layout(rect=[0, 0, 1, 0.93])

plt.show()


#======================================================================================